apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laa-submit-crime-forms.fullname" . }}
  labels:
    {{- include "laa-submit-crime-forms.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laa-submit-crime-forms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laa-submit-crime-forms.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.service_account.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
          # https://github.com/ministryofjustice/hmpps-utility-container-images
        - name: clamav
          image: ghcr.io/ministryofjustice/hmpps-clamav:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: clamav
              containerPort: 3310
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 3Gi
            requests:
              cpu: 10m
              memory: 1Gi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ "ALL" ]
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 30"] # Workaround for occasional lost requests - see https://github.com/puma/puma/blob/master/docs/kubernetes.md#running-puma-in-kubernetes
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: [ "ALL" ]
          env:
          {{ if .Values.redis.enabled }}
            - name: REDIS_PROTOCOL
              value: "redis"
            - name: REDIS_HOST
              value: {{ template "helm_deploy.redisUatHost" . }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.auth.password }}
          {{ else }}
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: crm-elasticache
                  key: primary_endpoint_address
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crm-elasticache
                  key: auth_token
          {{ end }}
          {{ if .Values.postgresql.enabled }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.postgresPassword }}
            - name: POSTGRES_HOST
              value: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.postgresql.auth.database }}
          {{ else }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: url
          {{ end }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: secret_key_base
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-dsn
                  key: url
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-bucket-output
                  key: bucket_name
            - name: GOVUK_NOTIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: notify-key
                  key: notify_key
            - name: AWS_REGION
              value: 'eu-west-2'
            - name: RACK_ENV
              value: 'production'
            - name: RAILS_ENV
              value: 'production'
            - name: RAILS_LOG_TO_STDOUT
              value: enabled
            - name: APP_STORE_URL
              value: {{ .Values.variables.appStore }}
            - name: ENV
              value: {{ .Values.variables.environment}}
            - name: LAA_PORTAL_SP_CERT
              valueFrom:
                secretKeyRef:
                  name: portal-sp-certificate
                  key: tls.crt
            - name: LAA_PORTAL_SP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: portal-sp-certificate
                  key: tls.key
            - name: LAA_PORTAL_IDP_METADATA_FILE
              value: {{ .Values.variables.portalIDPMetadataFile }}
            - name: SP_ENTITY_ID
              value: {{ .Values.variables.spEntityId }}
            - name: MAX_UPLOAD_SIZE_BYTES
              value: {{ mul .Values.variables.maxFileUploadBytes 1 | quote }}
            - name: ANALYTICS_TRACKING_ID
              valueFrom:
                secretKeyRef:
                  name: google-analytics
                  key: tracking_key
            - name: APP_STORE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: app-store-auth
                  key: tenant_id
            - name: APP_STORE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-store-auth
                  key: app_client_id
            - name: PROVIDER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-store-auth
                  key: provider_client_id
            - name: PROVIDER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-store-auth
                  key: provider_client_secret
            - name: SIDEKIQ_WEB_UI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sidekiq-auth
                  key: username
            - name: SIDEKIQ_WEB_UI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sidekiq-auth
                  key: password
            - name: CLAMBY_ENABLED
              value: 'true'
            - name: RAILS_SERVE_STATIC_FILES
              value: 'true'
            - name: EOL_URL
              value: {{ .Values.variables.eolUrl }}
            - name: HOSTS
              value: {{ range $index, $hostObject := .Values.ingress.hosts }}{{ if ne $index 0 }},{{ end }}{{ $hostObject.host }}{{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
