{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: application-metrics-monitor
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "laa-submit-crime-forms.fullname" . }}
  endpoints:
  - port: http
    interval: 15s
{{- end }}
