apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-submit-crime-forms.fullname" . }}
  labels:
    {{- include "laa-submit-crime-forms.labels" . | nindent 4 }}
    app: {{ include "laa-submit-crime-forms.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "laa-submit-crime-forms.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-submit-crime-forms.fullname" . }}-metrics-svc
  labels:
    {{- include "laa-submit-crime-forms.labels" . | nindent 4 }}
    service: {{ include "laa-submit-crime-forms.fullname" . }}-metrics-svc
    app: {{ include "laa-submit-crime-forms.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9394
      protocol: TCP
      name: metrics
  selector:
    metrics-target: {{ include "laa-submit-crime-forms.fullname" . }}-metrics-target
{{ if .Values.customErrorService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - port: 80
    targetPort: 8080
    name: http
{{ end }}
