apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-claim-non-standard-magistrate-fee-backend.fullname" . }}
  labels:
    {{- include "laa-claim-non-standard-magistrate-fee-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "laa-claim-non-standard-magistrate-fee-backend.selectorLabels" . | nindent 4 }}
