default: &default
  store_options:
    namespace: <%= Rails.env %>
    max_entries: 1000000
    max_age: null

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: production
