feature_flags:
  omniauth_test_mode:
    local: <%= ENV.fetch("OMNIAUTH_TEST_MODE", false) %>
    development: true
    uat: false
    production: false # must never be enabled in the live service
  postal_evidence:
    local: <%= ENV.fetch("POSTAL_EVIDENCE", false) %>
    development: false
    uat: false
    production: false
  maintenance_mode:
    local: <%= ENV.fetch("MAINTENANCE_MODE", false) %>
    development: false
    uat: true
    production: false

