# List of providers (office codes and/or emails)
# who can use the service (phased private MVP access).
#
# If a provider has more than one office code, then
# access is granted if any code is allowed.
#
localhost:
  office_codes:
    - 1A123B
    - 1K022G 
    - AAA
    - 0A719G
    - 1K022G

dev:
  office_codes:
    - 1A123B
    - 1K022G 
    - AAA
    - 0A719G
    - 1K022G

uat:
  office_codes:
    - 1A123B
    - 1K022G
    - 0Z981E
    - 0A719G
    - 1K022G

production:
  office_codes: []
