# List of providers (office codes and/or emails)
# who can use the service (phased private MVP access).
#
# If a provider has more than one office code, then
# access is granted if any code is allowed.
#
localhost:
  office_codes:
    1A123B: ['crm7', 'crm4', 'crm5']
    2A555X: ['crm7', 'crm4', 'crm5']
    1K022G: ['crm7', 'crm4', 'crm5']
    0A719G: ['crm7', 'crm4', 'crm5']
    0Z981E: ['crm7', 'crm4', 'crm5']
    AAAAAA: ['crm7']
    BBBBBB: ['crm4']
    CCCCCC: ['crm5']
    XXXXXX: ['crm7', 'crm4', 'crm5']
    ZZZZZZ: []

development:
  office_codes:
    1A123B: ['crm7', 'crm4', 'crm5']
    2A555X: ['crm7', 'crm4', 'crm5']
    1K022G: ['crm7', 'crm4', 'crm5']
    0A719G: ['crm7', 'crm4', 'crm5']
    0Z981E: ['crm7', 'crm4', 'crm5']
    AAAAAA: ['crm7']
    BBBBBB: ['crm4']
    CCCCCC: ['crm5']
    XXXXXX: ['crm7', 'crm4', 'crm5']
    ZZZZZZ: []

    # Test office for A.CLARKE (see 1Password for login), has eforms role
    0X416R: ['crm5', 'crm4']

    # Test office for 07RJONES (see 1Password for login), no eforms role
    0Q316L: ['crm5', 'crm4']

uat:
  office_codes:
    1A123B: ['crm7', 'crm4', 'crm5']
    2A555X: ['crm7', 'crm4', 'crm5']
    1K022G: ['crm7', 'crm4', 'crm5']
    0A719G: ['crm7', 'crm4', 'crm5']
    0Z981E: ['crm7', 'crm4', 'crm5']
    AAAAAA: ['crm7']
    BBBBBB: ['crm4']
    CCCCCC: ['crm5']
    XXXXXX: ['crm7', 'crm4', 'crm5']
    ZZZZZZ: []

production:
  office_codes:
    2N232W: ['crm7', 'crm4', 'crm5'] # dummy user/office
