# List of providers (office codes and/or emails)
# who can use the service (phased private MVP access).
#
# If a provider has more than one office code, then
# access is granted if any code is allowed.
#
# If ALL is specified then any authenticated user
# can access that service
#
localhost:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - CCCCCC
    - XXXXXX

development:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - CCCCCC
    - XXXXXX

    # Test user office from portal A.CLARK - with eForms role - (see 1Password for login details)
    - 0X416R

    # Test user office from portal 07RJONES - without eForms role - (see 1Password for login details)
    - 0Q316L

uat:
  office_codes:
    # Sixth CRM5 onboarding tranche - 04/07/2024
    - ALL

    # # dummy/testing office codes
    # - 1A123B
    # - 2A555X
    # - 1K022G
    # - 0A719G
    # - 0Z981E
    # - CCCCCC
    # - XXXXXX

    # # Test user office from portal A.CLARK - with eForms role - (see 1Password for login details)
    # - 0X416R

    # # Test user office from portal 07RJONES - without eForms role - (see 1Password for login details)
    # - 0Q316L

production:
  office_codes:
    # dummy user/office
    - 2N232W

    # First CRM5 onboarding tranche - 29/05/2024
    - 2L672A
    - 2M259N

    # Second CRM5 onboarding tranche - 06/06/2024
    - 2Q553U
    - 1U002F
    - 2M122P
    - 2M129X
    - 2M132A
    - 2M926N
    - 2P533K
    - 2P536N
    - 2Q241E
    - 2Q258Y
    - 2Q510X
    - 2Q511Y
    - 2Q512Z

    # Third CRM5 onboarding tranche - 12/06/2024
    - 0P276F
    - 0W966C
    - 2N791D
    - 2E061P
    - 2L888K

    # Fourth onboarding tranche - 20/6/2024
    - 0B378Y
    - 0C242M
    - 0D408E
    - 0F937D
    - 0G267M
    - 2P304L
    - 0G755T
    - 0A519P
    - 1E083N
    - 2N845M
    - 0H093K
    - 2Q484U
    - 0H322J
    - 0W953N
    - 1W341Y
    - 2M402U
    - 2M408A
    - 2M603M
    - 2N128H
    - 2N822M
    - 2N869N
    - 2Q621T
    - 2Q622U
    - 2Q623V
    - 0H530K
    - 0H849G
    - 2M467P
    - 0J153M
    - 2P439H
    - 0L057G
    - 0L858C
    - 0L951D
    - 0M392H
    - 0V656D
    - 0Z876Q
    - 2P333T
    - 0M058V
    - 0V774G
    - 1K905R
    - 2L669X
    - 2L705L
    - 2M411D
    - 2M413F
    - 2N829V
    - 2N915N
    - 2P048H
    - 2P208G
    - 2P417J
    - 2P418K
    - 2P419L
    - 2Q226N
    - 2Q229R
    - 2Q525N
    - 2Q528R
    - 2Q530U
    - 2Q531V
    - 2Q534Y
    - 2Q535Z
    - 2Q536A
    - 0M861T
    - 1J865L
    - 1J865L
    - 0N285D
    - 0N397A
    - 0N917Q
    - 1T004W
    - 0Q801N
    - 0R360W
    - 0R532H
    - 1P401R

    # Fifth onboarding tranche 27/06/24
    - 0U424P
    - 0W273Z
    - 2L947Z
    - 0U531F
    - 2M916C
    - 2P236M
    - 0U685Y
    - 0W953N
    - 1W341Y
    - 2M402U
    - 2M408A
    - 2M603M
    - 2N128H
    - 2N822M
    - 2N869N
    - 2Q621T
    - 2Q622U
    - 2Q623V
    - 0X395U
    - 0X724B
    - 2M425U
    - 2M426V
    - 2P409A
    - 2Q598T
    - 0Z015E
    - 0Z081B
    - 1P661Z
    - 0Z204K
    - 0Z550L
    - 1E721G
    - 1E724K
    - 2P854J
    - 1G141A
    - 2Q549P
    - 1K746U
    - 1K942G
    - 1Q161T
    - 1Q243G
    - 1Q522K
    - 1R621E
    - 2M416J
    - 2Q520H
    - 2A422J
    - 2Q502N
    - 2L728L
    - 2L755Q
    - 2M086A
    - 2M172U
    - 2N617P
    - 2M379U
    - 2Q409M
    - 2N876W
    - 2P080T
    - 2P103T
