# List of providers (office codes and/or emails)
# who can use the service (phased private MVP access).
#
# If a provider has more than one office code, then
# access is granted if any code is allowed.
#
# If ALL is specified then any authenticated user
# can access that service
#
localhost:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - AAAAAA
    - XXXXXX

development:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - AAAAAA
    - XXXXXX

    # Test user office from portal A.CLARK - with eForms role - (see 1Password for login details)
    # - 0X416R

    # Test user office from portal 07RJONES - without eForms role - (see 1Password for login details)
    # - 0Q316L

uat:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - AAAAAA
    - XXXXXX

    # Test user office from portal A.CLARK - with eForms role - (see 1Password for login details)
    # - 0X416R

    # Test user office from portal 07RJONES - without eForms role - (see 1Password for login details)
    # - 0Q316L

production:
  office_codes:
    # dummy user/office
    - 2N232W

    # First CRM7 onboarding tranche - 19/08/24
    - 0W160B
    - 2M075N
    - 2M847C
    - 2N849R
    - 2P203B
    - 2P328M
    - 2P475X
    - 2P476Y
    - 2P479B
    - 2P481D
    - 2Q202M
    - 2Q203N
    - 2Q268J
    - 2Q269K
    - 2Q413R
    - 2Q414T
    - 2Q613J
    - 1L461W
    - 1U002F
    - 2M122P
    - 2M129X
    - 2M132A
    - 2M926N
    - 2P533K
    - 2P536N
    - 2Q241E
    - 2Q258Y
    - 2Q510X
    - 2Q511Y
    - 2Q512Z

    # Second CRM7 onboarding tranche - 22/08/24
    - 0W953N
    - 1W341Y
    - 2M402U
    - 2M408A
    - 2M603M
    - 2N128H
    - 2N822M
    - 2N869N
    - 2Q621T
    - 2Q622U
    - 2Q623V
    - 0M058V
    - 0V774G
    - 1K905R
    - 2L669X
    - 2L705L
    - 2M411D
    - 2M413F
    - 2N829V
    - 2N915N
    - 2P048H
    - 2P208G
    - 2P417J
    - 2P418K
    - 2P419L
    - 2Q226N
    - 2Q229R
    - 2Q525N
    - 2Q528R
    - 2Q530U
    - 2Q531V
    - 2Q534Y
    - 2Q535Z
    - 2Q536A
    - 0R225Z
    - 2C101J
    - 2F801F
    - 2M030P
    - 2N823N
    - 2N824P
    - 2N842J
    - 2P169P
    - 2P287T
    - 2P288U
    - 2Q419Y
    - 2Q422B
    - 0G267M
    - 2P304L
    - 2A041V

    # Second (and a half) CRM7 onboarding tranche - 27/08/24
    - 0R360W
    - 0R532H
    - 1P401R
    - 0B491W
    - 0K689G
    - 0V669T
    - 2Q406J
    - 2M244X
    - 2P281L
    - 2Q248M
    - 1R646G
    - 2P204C
    - 2Q568K
    - 2Q569L
    - 2Q570M
    - 1T985M
    - 1Q921U
