# List of providers (office codes and/or emails)
# who can use the crm4/PA service (phased private MVP access).
#
# If a provider has more than one office code, then
# access is granted if any code is allowed.
#
# If ALL is specified then any authenticated user
# can access that service
#
localhost:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - BBBBBB
    - XXXXXX

development:
  office_codes:
    # dummy/testing office codes
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - BBBBBB
    - XXXXXX

    # Test user office from portal A.CLARK - with eForms role - (see 1Password for login details)
    - 0X416R

    # Test user office from portal 07RJONES - without eForms role - (see 1Password for login details)
    - 0Q316L

uat:
  office_codes:
    - 1A123B
    - 2A555X
    - 1K022G
    - 0A719G
    - 0Z981E
    - BBBBBB
    - XXXXXX

    # Test user office from portal A.CLARK - with eForms role - (see 1Password for login details)
    - 0X416R

    # Test user office from portal 07RJONES - without eForms role - (see 1Password for login details)
    - 0Q316L

production:
  office_codes:
    # dummy user/office
    # - 2N232W

    # First CRM4 onboarding tranche - 04/06/2024
    - 1U002F
    - 2M122P
    - 2M129X
    - 2M132A
    - 2M926N
    - 2P533K
    - 2P536N
    - 2Q241E
    - 2Q258Y
    - 2Q510X
    - 2Q511Y
    - 2Q512Z

    # Second CRM4 onboarding tranche - 11/06/2024
    - 0W160B
    - 2M075N
    - 2M847C
    - 2N849R
    - 2P203B
    - 2P328M
    - 2P475X
    - 2P476Y
    - 2P479B
    - 2P481D
    - 2Q202M
    - 2Q203N
    - 2Q268J
    - 2Q269K
    - 2Q413R
    - 2Q414T
    - 2Q613J
    - 1L461W
    - 0W953N
    - 1W341Y
    - 2M402U
    - 2M408A
    - 2M603M
    - 2N128H
    - 2N822M
    - 2N869N
    - 2Q621T
    - 2Q622U
    - 2Q623V

    # Second and a half (2.5) CRM4 onboarding tranche - 13/06/2024
    - 0M058V
    - 0V774G
    - 1K905R
    - 2L669X
    - 2L705L
    - 2M411D
    - 2M413F
    - 2N829V
    - 2N915N
    - 2P048H
    - 2P208G
    - 2P417J
    - 2P418K
    - 2P419L
    - 2Q226N
    - 2Q229R
    - 2Q525N
    - 2Q528R
    - 2Q530U
    - 2Q531V
    - 2Q534Y
    - 2Q535Z
    - 2Q536A
    - 0R225Z
    - 2C101J
    - 2F801F
    - 2M030P
    - 2N823N
    - 2N824P
    - 2N842J
    - 2P169P
    - 2P287T
    - 2P288U
    - 2Q419Y
    - 2Q422B
    - 0G267M
    - 2P304L

    # Third CRM4 onboarding tranche - 18/06/2024
    - 0A519P
    - 0G755T
    - 1E083N
    - 2N845M
    - 2B921N
    - 2P255H
    - 2P256J
    - 2P257K
    - 2P258L
    - 2Q305Z
    - 1V481N
    - 2L813D
    - 2Q343Q
    - 2M103U
    - 2M105W
    - 2M107Y
    - 2M109A
    - 2M110B
    - 2M111C
    - 2M112D
    - 2M113E
    - 2P002H
    - 2P005L
    - 2P316Z
    - 2P317A
    - 2P318B
    - 2P344E
    - 1Z962J
    - 2L758U
    - 2P268X
    - 2P269Y
    - 0D180G
    - 0N496H
    - 2L579Z
    - 2M250D
    - 2M338Z
    - 0V391Q
    - 0B836W
    - 2M305N
    - 2P348J
    - 0W952M
    - 1V483Q
    - 1N042P
    - 2M884T
    - 2Q207T
    - 2Q263D
    - 2Q278V
    - 2N876W
    - 1E921Z
    - 2Q322T
    - 1H161J
    - 2D601P
    - 2L557A
    - 0L418Z
    - 0V482P
    - 0C259F

    # Fourth onboarding tranche - 21/06/2024
    - 0K919G
    - 0W162D
    - 0W396H
    - 2P398N
    - 2Q506T
    - 2Q507U

    # Eighth onboarding tranche - 22/07/2024
    - 0A719G
    - 0X987M
    - 2M036W
    - 2M835P
    - 2P057T
    - 2P335V
    - 2P336W
    - 2Q649Y
    - 0N235Z
    - 1T422A
    - 2C002B
    - 2P322F
    - 2Q543H
    - 0C548V
    - 1J241H
    - 2Q315K
    - 2Q316L
    - 0L951D
    - 0M392H
    - 0V656D
    - 0Z876Q
    - 2P333T
    - 1R646G
    - 2P204C
    - 2Q568K
    - 2Q569L
    - 2Q570M
    - 2P493R
    - 1B281T
    - 2P277G
    - 0G769H
    - 2P516R
    - 2P517T
    - 0Q319P
    - 2L828V
    - 2P310T
    - 0X724B
    - 2M425U
    - 2M426V
    - 2P409A
    - 2Q598T
    - 2M359X
    - 2N115U
    - 0X218B
    - 2M435E
    - 2Q561C
    - 0L783W
    - 0A018V
    - 2L728L
    - 0B620L
    - 2F081Y
    - 2M283P
    - 0B378Y
    - 0R360W
    - 0R532H
    - 1P401R
    - 2L672A
    - 0M015Y
    - 0Y060R
    - 2P104U
    - 2P965E
    - 0L582C
    - 0V995X
    - 2Q196F
    - 2Q375A
    - 0W534H
    - 2L694Z
    - 2M350M
    - 2P038X
    - 2P308Q
    - 2Q437T
