name: "Delete UAT deployment"
description: 'Deletes a UAT deployment with a name that matches the merged or closed branch'
inputs:
  k8s_cluster:
    description: "Kubernetes cluster name"
    required: true
  k8s_cluster_cert:
    description: "Kubernetes cluster certificate"
    required: true
  k8s_namespace:
    description: "Kubernetes cluster namespace"
    required: true
  k8s_token:
    description: "Kubernetes authentication token"
    required: true
  pod_name:
    description: "Name of the pod to run it on"
    required: true

runs:
  using: "composite"
  steps:
    - name: Authenticate to the cluster
      id: authenticate_to_cluster
      shell: bash
      env:
        K8S_CLUSTER: ${{ inputs.k8s_cluster }}
        K8S_CLUSTER_CERT: ${{ inputs.k8s_cluster_cert }}
        K8S_NAMESPACE: ${{ inputs.k8s_namespace }}
        K8S_TOKEN: ${{ inputs.k8s_token }}
        POD_NAME: ${{ inputs.pod_name }}
      run: |
        echo "${K8S_CLUSTER_CERT}" > ./ca.crt
        kubectl config set-cluster ${K8S_CLUSTER} --certificate-authority=./ca.crt --server=https://${K8S_CLUSTER}
        kubectl config set-credentials circleci --token=${K8S_TOKEN}
        kubectl config set-context ${K8S_CLUSTER} --cluster=${K8S_CLUSTER} --user=circleci --namespace=${K8S_NAMESPACE}
        kubectl config use-context ${K8S_CLUSTER}

    - name: Run freshclam
      id: run_freshclam
      shell: bash
      run: |
        kubectl exec ${POD_NAME} -it -- freshclam
