# Default values for laa-submit-crime-forms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: laa-submit-crime-forms-app
fullnameOverride: laa-submit-crime-forms-app

securityContext:
  #  capabilities:
  #    drop:
  #    - ALL
  #  readOnlyRootFilesystem: true
  #  runAsNonRoot: true
  #  runAsUser: 10000
  #  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80
  internalPort: 3000
  workerPort: 7433

ingress:
  enabled: true
  namespace: laa-submit-crime-forms-prod
  className: modsec
  annotations:
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=6"
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
    external-dns.alpha.kubernetes.io/set-identifier: laa-submit-crime-forms-app-laa-submit-crime-forms-prod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - host: submit-crime-forms.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
          service:
            name: laa-submit-crime-forms-dev
            port:
              number: 3000
  tls:
    - hosts:
      - submit-crime-forms.service.justice.gov.uk
      secretName: laa-submit-crime-forms-cert

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 10m
    memory: 500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

variables:
  environment: production
  portalIDPMetadataFile: config/laa_portal/metadata/prod.xml
  spEntityId: LAA_Portal_CRM7_Prod
  appStore: https://laa-crime-application-store-prod.apps.live.cloud-platform.service.justice.gov.uk
  maxFileUploadBytes: 10485760
  eolUrl: https://apply-for-extension-of-upper-limits.form.service.justice.gov.uk/
  enableSyncTriggerEndpoint: 'false'
  allowIndexing: 'true'

service_account:
  name: laa-submit-crime-forms-prod-irsa

# Instead of a temporary postgres pod we use RDS
postgresql:
  enabled: false

# Instead of a temporary redis pod we use Elasticache
redis:
  enabled: false
