# Default values for laa-claim-non-standard-magistrate-fee-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: laa-claim-non-standard-magistrate-fee-backend-app
fullnameOverride: laa-claim-non-standard-magistrate-fee-backend-app

securityContext:
  #  capabilities:
  #    drop:
  #    - ALL
  #  readOnlyRootFilesystem: true
  #  runAsNonRoot: true
  #  runAsUser: 10000
  #  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80
  internalPort: 3000

ingress:
  enabled: true
  namespace: laa-claim-non-standard-magistrate-fee-prod
  className: modsec
  annotations: 
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAction "id:900110,phase:1,nolog,pass,t:none,setvar:tx.inbound_anomaly_score_threshold=6"
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE"
    external-dns.alpha.kubernetes.io/set-identifier: laa-claim-non-standard-magistrate-fee-backend-app-laa-claim-non-standard-magistrate-fee-prod-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
  hosts:
    - host: crm7prod.apps.live.cloud-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
          service:
            name: laa-claim-non-standard-magistrate-fee-dev
            port:
              number: 3000
  tls:
    - hosts:
      - crm7prod.apps.live.cloud-platform.service.justice.gov.uk

resources:
  limits:
    cpu: 500m
    memory: 125Mi
  requests:
    cpu: 10m
    memory: 125Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

secrets:
  environment: production