# Default values for laa-submit-crime-forms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

namespace: laa-submit-crime-forms-uat

serviceMonitor:
  enabled: false

image:
  repository: nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: laa-submit-crime-forms-app
fullnameOverride: laa-submit-crime-forms-app

securityContext:
  #  capabilities:
  #    drop:
  #    - ALL
  #  readOnlyRootFilesystem: true
  #  runAsNonRoot: true
  #  runAsUser: 10000
  #  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80
  internalPort: 3000
  workerPort: 7433

ingress:
  enabled: true
  className: modsec
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: laa-submit-crime-forms-app-laa-submit-crime-forms-uat-green
  hosts:
    - host: uat.submit-crime-forms.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
          service:
            name: laa-submit-crime-forms-dev
            port:
              number: 3000
  tls:
    - hosts:
      - uat.submit-crime-forms.service.justice.gov.uk
      secretName: laa-submit-crime-forms-cert

app_resources:
  limits:
    cpu: 500m
    memory: 4Gi
  requests:
    cpu: 10m
    memory: 500Mi

clamav_resources:
  limits:
    cpu: 500m
    memory: 4Gi
  requests:
    cpu: 10m
    memory: 500Mi

worker_resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 10m
    memory: 500Mi

variables:
  environment: uat
  portalIDPMetadataFile: config/laa_portal/metadata/uat.xml
  spEntityId: LAA_Portal_CRM7_UAT
  appStore: http://laa-crime-application-store-app.laa-crime-application-store-uat.svc.cluster.local
  maxFileUploadBytes: 10485760
  eolUrl: https://apply-for-extension-of-upper-limits.dev.form.service.justice.gov.uk/
  enableSyncTriggerEndpoint: 'false'
  allowIndexing: 'false'

service_account:
  name: laa-submit-crime-forms-uat-irsa

# Instead of a temporary postgres pod we use RDS
postgresql:
  enabled: false

# Instead of a temporary redis pod we use Elasticache
redis:
  enabled: false
